version: '3.9'
services:
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: flask
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '3050:80'
        depends_on:
            - api
    api:
        build:
            dockerfile: Dockerfile
            context: ./server
        ports:
            - "8000:5000"
        volumes:
            - /venv
            - ./server:/app
        environment:
            - ENV FLASK_ENV=development
            - APIHOST=127.0.0.1
            - APIPORT=8000
            - FLASK_ENV=development
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=flask