version: '3.9'
services:
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '3050:80'
        depends_on:
            - api
    api:
        build:
            dockerfile: Dockerfile
            context: ./server
        volumes:
            - /venv
            - ./server:/app
        ports:
            - '5000:5000'
        environment:
            - FLASK_ENV=development
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on:
            - postgres
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
